export const DEFAULT_AUTOCOMPLETE_MINIMUM_QUERY_LENGTH = 5;
export const DEFAULT_BESPOKE_CATALOG_QUERY_SIZE = 200;
export const DEFAULT_MAX_RECENTLY_ASSIGNED_SKU_GROUPS = 5;
export const DEFAULT_METRC_DATA_QUERY_LIMIT = 200;
