version: "3.6"
services:
  bespoke-postgres:
    image: postgres:11
    container_name: bespoke-postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - bespoke_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  bespoke-graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    container_name: bespoke-graphql-engine
    ports:
      - 8080:8080
    depends_on:
      - bespoke-postgres
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@bespoke-postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE"}'
    healthcheck:
      test: "wget --quiet --spider http://localhost:8080/healthz || exit 1"
      interval: 30s
      timeout: 3s
volumes:
  bespoke_db_data:
