[tool.pylint]
max-line-length = 100
jobs = 0 # setting to 0 detects the number of available processors
message_control.disable = [
  "too-many-nested-blocks"
]

[tool.yapf]
based_on_style = "pep8"
align_closing_bracket_with_visual_indent = false
allow_multiline_lambdas = true
allow_split_before_dict_value = false
arithmetic_precedence_indication = false
blank_line_before_nested_class_or_def = false
blank_line_before_module_docstring = false
blank_lines_around_top_level_definition = 1
coalesce_brackets = true
column_limit = 100
continuation_align_style = "space"
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
force_multiline_dict = true
indent_width = 4
indent_blank_lines = true
spaces_around_power_operator = true
spaces_around_default_or_named_assign = true
spaces_around_dict_delimiters = true
spaces_around_subscript_colon = true
spaces_around_tuple_delimiters = true
spaces_before_comment = 2
SPLIT_BEFORE_NAMED_ASSIGNS = false
space_between_ending_comma_and_closing_bracket = true
space_inside_brackets = true
split_arguments_when_comma_terminated = true
split_all_comma_separated_values = false
split_all_top_level_comma_separated_values = true
