version: "3.6"
services:
  bespoke-postgres-ci:
    image: postgres:11
    container_name: bespoke-postgres-ci
    restart: always
    volumes:
      - bespoke_db_data_ci:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      EVENT_TRIGGER_URL: http://localhost:7002
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  bespoke-graphql-engine-ci:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    container_name: bespoke-graphql-engine-ci
    depends_on:
      - bespoke-postgres-ci
    restart: always
    volumes:
      - ./graphql-server/migrations:/hasura-migrations
      - ./graphql-server/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@bespoke-postgres-ci:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_LOG_LEVEL: error
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE"}'
      ASYNC_SERVER_API_KEY: bespoke-async-server-api-key
      ASYNC_SERVER_BASE_URL: "http://bespoke-api-server-ci:7002"
  bespoke-api-server-ci:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: bespoke-api-server-ci
    depends_on:
      - bespoke-postgres-ci
    restart: always
    volumes:
      - ./api-server/src:/app/src/
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@bespoke-postgres-ci:5432/postgres
  bespoke-app-ci:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bespoke-app-ci
    depends_on:
      - bespoke-postgres-ci
      - bespoke-graphql-engine-ci
      - bespoke-api-server-ci
    environment:
      - HOST=bespoke-app-ci
      - REACT_APP_BESPOKE_API_ENDPOINT=http://bespoke-api-server-ci:7002
      - REACT_APP_BESPOKE_GRAPHQL_ENDPOINT=http://bespoke-graphql-engine-ci:8080/v1/graphql
      - REACT_APP_BESPOKE_WS_GRAPHQL_ENDPOINT=ws://bespoke-graphql-engine-ci:8080/v1/graphql
    volumes:
      - ./app:/app
      - /app/node_modules
  bespoke-cypress-ci:
    image: cypress
    build:
      context: ./app
      dockerfile: Dockerfile-cypress
    container_name: bespoke-cypress-ci
    depends_on:
      - bespoke-postgres-ci
      - bespoke-graphql-engine-ci
      - bespoke-api-server-ci
      - bespoke-app-ci
    environment:
      - CYPRESS_baseUrl=http://bespoke-app-ci:3006
      - CYPRESS_apiServerUrl=http://bespoke-api-server-ci:7002
      - CYPRESS_isDocker=true
    command: ./wait-for-it.sh bespoke-app-ci:3006 -t 300 -- npx cypress run
    volumes:
      - ./app/cypress:/app/cypress
      - ./app/cypress.json:/app/cypress.json

volumes:
  bespoke_db_data_ci:
