version: "3.6"
services:
  bespoke-postgres-cypress:
    image: postgres:11
    container_name: bespoke-postgres-cypress
    restart: always
    volumes:
      - bespoke_db_data_cypress:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      EVENT_TRIGGER_URL: http://localhost:7002
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  bespoke-graphql-engine-cypress:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    container_name: bespoke-graphql-engine-cypress
    ports:
      - 8081:8080
    depends_on:
      - bespoke-postgres-cypress
    restart: always
    volumes:
      - ./graphql-server/migrations:/hasura-migrations
      - ./graphql-server/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@bespoke-postgres-cypress:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_LOG_LEVEL: error
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE"}'
      ASYNC_SERVER_API_KEY: bespoke-async-server-api-key
      ASYNC_SERVER_BASE_URL: "http://bespoke-api-server-cypress:7002"
  bespoke-api-server-cypress:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: bespoke-api-server-cypress
    ports:
      - 7002:7002
    depends_on:
      - bespoke-postgres-cypress
    restart: always
    volumes:
      - ./api-server/src:/app/src/
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@bespoke-postgres-cypress:5432/postgres
  bespoke-app-cypress:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: bespoke-app-cypress
    ports:
      - 3006:3006
    depends_on:
      - bespoke-postgres-cypress
      - bespoke-graphql-engine-cypress
      - bespoke-api-server-cypress
    environment:
      - HOST=bespoke-app-cypress
      - REACT_APP_BESPOKE_API_ENDPOINT=http://localhost:7002
      - REACT_APP_BESPOKE_GRAPHQL_ENDPOINT=http://localhost:8081/v1/graphql
      - REACT_APP_BESPOKE_WS_GRAPHQL_ENDPOINT=ws://localhost:8081/v1/graphql
    volumes:
      - ./app:/app
      - /app/node_modules

volumes:
  bespoke_db_data_cypress:
