-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."debt_facility_capacities" add column "changed_by" uuid
--  null;
