table:
  schema: public
  name: ebba_application_files
object_relationships:
  - name: ebba_application
    using:
      foreign_key_constraint_on: ebba_application_id
  - name: file
    using:
      foreign_key_constraint_on: file_id
insert_permissions:
  - role: bank_admin
    permission:
      check: {}
      columns:
        - ebba_application_id
        - file_id
      backend_only: false
  - role: company_admin
    permission:
      check:
        ebba_application:
          company_id:
            _eq: X-Hasura-Company-Id
      columns:
        - ebba_application_id
        - file_id
      backend_only: false
select_permissions:
  - role: bank_admin
    permission:
      columns:
        - ebba_application_id
        - file_id
      filter: {}
  - role: bank_read_only
    permission:
      columns:
        - ebba_application_id
        - file_id
      filter: {}
  - role: company_admin
    permission:
      columns:
        - ebba_application_id
        - file_id
      filter:
        ebba_application:
          company_id:
            _eq: X-Hasura-Company-Id
  - role: company_read_only
    permission:
      columns:
        - ebba_application_id
        - file_id
      filter:
        ebba_application:
          company_id:
            _eq: X-Hasura-Company-Id
delete_permissions:
  - role: bank_admin
    permission:
      filter: {}
  - role: company_admin
    permission:
      filter:
        ebba_application:
          company_id:
            _eq: X-Hasura-Company-Id
