table:
  schema: public
  name: company_settings
object_relationships:
  - name: client_success_user
    using:
      foreign_key_constraint_on: client_success_user_id
  - name: active_borrowing_base
    using:
      foreign_key_constraint_on: active_borrowing_base_id
  - name: active_ebba_application
    using:
      foreign_key_constraint_on: active_ebba_application_id
  - name: active_financial_report
    using:
      foreign_key_constraint_on: active_financial_report_id
  - name: advances_bank_account
    using:
      foreign_key_constraint_on: advances_bank_account_id
  - name: advances_bespoke_bank_account
    using:
      foreign_key_constraint_on: advances_bespoke_bank_account_id
  - name: collections_bank_account
    using:
      foreign_key_constraint_on: collections_bank_account_id
  - name: collections_bespoke_bank_account
    using:
      foreign_key_constraint_on: collections_bespoke_bank_account_id
  - name: company
    using:
      foreign_key_constraint_on: company_id
  - name: metrc_api_key
    using:
      foreign_key_constraint_on: metrc_api_key_id
  - name: business_development_user
    using:
      foreign_key_constraint_on: business_development_user_id
  - name: underwriter_user
    using:
      foreign_key_constraint_on: underwriter_user_id
select_permissions:
  - role: bank_admin
    permission:
      columns:
        - client_success_user_id
        - active_borrowing_base_id
        - active_ebba_application_id
        - active_financial_report_id
        - advances_bank_account_id
        - advances_bespoke_bank_account_id
        - collections_bank_account_id
        - collections_bespoke_bank_account_id
        - company_id
        - created_at
        - custom_messages_payload
        - feature_flags_payload
        - has_autofinancing
        - id
        - is_autogenerate_repayments_enabled
        - is_dummy_account
        - metrc_api_key_id
        - payor_agreement_docusign_template
        - business_development_user_id
        - underwriter_user_id
        - two_factor_message_method
        - updated_at
        - vendor_agreement_docusign_template
        - vendor_onboarding_link
      filter: {}
  - role: bank_read_only
    permission:
      columns:
        - client_success_user_id
        - active_borrowing_base_id
        - active_ebba_application_id
        - active_financial_report_id
        - advances_bank_account_id
        - advances_bespoke_bank_account_id
        - collections_bank_account_id
        - collections_bespoke_bank_account_id
        - company_id
        - created_at
        - custom_messages_payload
        - feature_flags_payload
        - has_autofinancing
        - id
        - is_autogenerate_repayments_enabled
        - is_dummy_account
        - metrc_api_key_id
        - payor_agreement_docusign_template
        - business_development_user_id
        - underwriter_user_id
        - two_factor_message_method
        - updated_at
        - vendor_agreement_docusign_template
        - vendor_onboarding_link
      filter: {}
  - role: company_admin
    permission:
      columns:
        - active_borrowing_base_id
        - active_ebba_application_id
        - active_financial_report_id
        - advances_bank_account_id
        - collections_bank_account_id
        - company_id
        - custom_messages_payload
        - feature_flags_payload
        - has_autofinancing
        - id
        - is_autogenerate_repayments_enabled
        - payor_agreement_docusign_template
        - two_factor_message_method
        - vendor_agreement_docusign_template
        - vendor_onboarding_link
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
  - role: company_read_only
    permission:
      columns:
        - active_borrowing_base_id
        - active_ebba_application_id
        - active_financial_report_id
        - advances_bank_account_id
        - collections_bank_account_id
        - company_id
        - custom_messages_payload
        - feature_flags_payload
        - has_autofinancing
        - id
        - is_autogenerate_repayments_enabled
        - payor_agreement_docusign_template
        - two_factor_message_method
        - vendor_agreement_docusign_template
        - vendor_onboarding_link
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
  - role: invoice_reviewer
    permission:
      columns:
        - collections_bespoke_bank_account_id
        - id
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
update_permissions:
  - role: bank_admin
    permission:
      columns:
        - advances_bank_account_id
        - advances_bespoke_bank_account_id
        - collections_bank_account_id
        - collections_bespoke_bank_account_id
        - has_autofinancing
        - is_dummy_account
        - payor_agreement_docusign_template
        - two_factor_message_method
        - vendor_agreement_docusign_template
        - vendor_onboarding_link
      filter: {}
      check: null
  - role: company_admin
    permission:
      columns:
        - advances_bank_account_id
        - collections_bank_account_id
      filter:
        company_id:
          _eq: X-Hasura-Company-Id
      check: null
