-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."vendor_change_requests" add column "requesting_company_id" uuid
--  null;
