name: CI Cypress

on:
  push:
    branches:
      - staging
    paths:
      - "services/app/**"
  pull_request:
    branches:
      - staging
    paths:
      - "services/app/**"

jobs:
  cypress:
    defaults:
      run:
        working-directory: services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.ci.yaml build
      - run: docker-compose -f docker-compose.ci.yaml up --abort-on-container-exit --exit-code-from bespoke-cypress-ci
      # Confirm whether Cypress ran correctly by looking at output file
      - run: cat app/cypress/results/output.xml
